### ISSUE TITLE
BBC-1.1 Quick Run

### ISSUE THREAD

**Issue by brianprichardson** [maksimKorzh/bbc#3]
Just FYI...
This version still has illegal moves in the PV according to cutechess-cli.
However, there were no time forfeits with 1.1 (1.0 had many).

Match results:
Score of BBC-10 vs BBC-11: 27 - 103 - 8  [0.225] 138
...      BBC-10 playing White: 15 - 50 - 3  [0.243] 68
...      BBC-10 playing Black: 12 - 53 - 5  [0.207] 70
...      White vs Black: 68 - 62 - 8  [0.522] 138
Elo difference: -215.2 +/- 68.0, LOS: 0.0 %, DrawRatio: 5.8 %

**Comment by maksimKorzh** [comment]
Thanks, I still can't understand what kind of illegal moves in PV you're talking about, can you give me some logs please?
I tried to work with cutechess-cli but it annoys me so much that I can't do anything to myself to start using in.
I just want to get a clear understanding on what does cutechess mean by saying illegal move because that doesn't seem for me to be possible.
PLEASE gimme some logs with particular PV so I can prove that the move is illegal

**Comment by brianprichardson** [comment]
D:\Cutechess-cli>cutechess-cli -debug -each tc=0:10+1.0 restart=on -engine conf=BBC-10 -engine conf=BBC-11 -games 12000 -wait 1000 -ratinginterval 10 -tb E:/syzygy;E:/syzygy-7 -tbpieces 7 -openings file=D:/Cutechess-cli/book_3moves_cp25-49_13580pos.pgn start=1 -repeat -concurrency 1 -pgnout book_3moves_cp25-49_13580pos.pgn-BBC-10_v_BBC-11.pgn min fi > log.txt
Warning: Illegal PV move h8h7 from BBC-11 (1)
Warning: PV: Kh7 Qxe6 Nf2+ Kg2 Nd3+ Kh3 h8h7
Warning: Illegal PV move f3g2 from BBC-11 (1)
Warning: PV: Nf2+ Kg2 Nd3+ Kh3 Ne5 Qxe5 Bxe5 Re7 Qd3 f3g2
Warning: Illegal PV move e6g4 from BBC-10 (0)
Warning: PV: Kg2 Ng4+ Kh3 Nf2+ e6g4
Warning: Illegal PV move e6g4 from BBC-10 (0)
Warning: PV: Kg2 Ng4+ Kh3 Nf2+ e6g4
Warning: Illegal PV move e6f5 from BBC-11 (1)
Warning: PV: Ng4+ Kh3 Nf2+ e6f5
Warning: Illegal PV move e6f6 from BBC-10 (0)
Warning: PV: Kh3 Nf2+ e6f6
Warning: Illegal PV move e6g4 from BBC-10 (0)
Warning: PV: Kh3 Nf2+ e6g4
Warning: Illegal PV move h3g4 from BBC-10 (0)
Warning: PV: Kh3 Nf2+ h3g4
Warning: Illegal PV move e6g4 from BBC-11 (1)
Warning: PV: Nf2+ e6g4
Warning: Illegal PV move b2c3 from BBC-11 (1)
Warning: PV: Nf2+ b2c3
Warning: Illegal PV move e6g4 from BBC-11 (1)
Warning: PV: Nf2+ e6g4
Warning: Omitted incomplete game 1

D:\Cutechess-cli>

[log.txt](https://github.com/maksimKorzh/bbc/files/5304947/log.txt)

**Comment by maksimKorzh** [comment]
Now this is what need, thank you!

**Comment by maksimKorzh** [comment]
@brianprichardson it seems like I've fixed illegal move in PV bug.
Here's the fixed version:
[(https://github.com/maksimKorzh/bbc/blob/master/src/bbc_1.2a.c)]
Also I've optimized interpolation so now it's done only ones as suggested by Pedro Castro, so should be around 10-15 ELO stronger compared to bbc 1.1

I was testing in cutechess-cli (damn, that was a challenge!) and didn't get any warnings. Could you please test it on your side if still interested?

What the problem was (IMO):
I was updating PV length after returning 3 fold repetition draw score so the illegal move was attached to the PV becuase PV length wasn't adjusted correctly, now when I set up PV length before 3 fold repetition (where it should be) everything seems working ok.

**Comment by brianprichardson** [comment]
No more invalid PV move warning, but 1.2a has losses on time now.
Will run match again this time with logging.

**Comment by brianprichardson** [comment]
search for 'on time' to see time losses
[cutechess.log](https://github.com/maksimKorzh/bbc/files/5320699/cutechess.log)

**Comment by maksimKorzh** [comment]
Hmmm... very strange because I didn't change timing at all, now assuming time left for both sides:
go wtime 1029 btime 1036 winc 1000 binc 1000
what's wrong in loosing on time?

**Comment by maksimKorzh** [comment]
@brianprichardson 
Here's report by Pedro Castro (bbc_1.2a vs bbc_1.1):
bbc1.2a only interpolación Win 73 games, Lost 58, Draw 69.
Elo for bbc1.2a is:  +26.1
But error here is:  +/- 39.1

Timings in both engines are 100% the same.
I just can't get why engine can't lose on time??
Is that a bug??

**Comment by brianprichardson** [comment]
Losing on time is not acceptable, especially with a 1 second increment.
It distorts match results.
Suppose your engine is in a strong winning position and then gets flagged for a time loss.

**Comment by maksimKorzh** [comment]
@brianprichardson it seems I've fixed lose on increment bug, please see this version:
https://github.com/maksimKorzh/bbc/blob/master/src/bbc_1.2b.c
Also it finally brought commented out evaluation features, so version 1.2b should be stronger compared to 1.2a

**Comment by brianprichardson** [comment]
No more time losses with 1.2b version at 10 sec + 1 sec increment.

**Comment by maksimKorzh** [comment]
@brianprichardson thanks, Brian
